name: Docker build and push

on:
    push:
        branches: [main]

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Docker Checkout
              uses: actions/checkout@v4

            - name: Login to Dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build and Push to Docker Hub
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: |
                    ${{ vars.DOCKERHUB_USER }}/github-actions-app:${{ github.ref_name }}




