name : Hello
on: 
  push:
    branches : [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to the users
        run: echo "Hello Dosto!"
      - name: Greet the current user
        run: echo "Hello $USER"
